'use client';
import { useEffect, useRef, useState } from 'react';
import styles from './AnikAIWidget.module.css';

const starters = ['What is LYKA?','Show my status','How does the hunt work?','Open Maths Lab'];
const rooms = [['HQ','/hq'],['Roast','/roast'],['Maths','/maths-sir'],['Orbit','/mission'],['Vault','/memes'],['Archive','/archive'],['LMAO','/lmao'],['Live Feed','/live'],['Incident Room','/incidents'],['Photos','/photos']];

export function AnikAIWidget({ route='/hq', ghee=78, cool=0 }) {
  const [open,setOpen]=useState(false); const [messages,setMessages]=useState([{role:'assistant',content:'ANIK.EXE online. Bol bhai — LYKA ka status, rooms, hunt ya normal question pooch.'}]); const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const endRef=useRef(null);
  useEffect(()=>endRef.current?.scrollIntoView({behavior:'smooth'}),[messages,busy]);
  async function ask(text){const value=String(text||'').trim();if(!value||busy)return;const next=[...messages,{role:'user',content:value}];setMessages(next);setInput('');setBusy(true);const n=value.toLowerCase();let local=null;if(n==='status'||n.includes('my status'))local='LIVE STATUS\nRoute: '+route+'\nGhee: '+ghee+'%\nCool events: '+cool+'\nSystem: ONLINE';else if(n.includes('hunt'))local='SECRET HUNT\n10 hidden field artifacts are scattered across LYKA. Your progress is shown in HUNT. Press H to open the hunt panel.';else if(n.includes('rooms'))local='ROOM INDEX\n'+rooms.map(item=>'• '+item[0]+' — '+item[1]).join('\n');else if(n.includes('maths lab')||n.includes('open maths'))local='MATHS LAB\nTimed hard questions, streaks and focus modes live in the Maths room.';else if(n==='help'||n.includes('what can you do'))local='ANIK.EXE COMMANDS\nTry: status, rooms, hunt, maths lab or roast. General questions work when the AI backend is connected.';else if(n.includes('roast'))local='ROAST LAB\nGo to /roast and hit BAN GAYA COOL.';if(local){setMessages(prev=>[...prev,{role:'assistant',content:local}]);setBusy(false);return;}try{const res=await fetch('/api/lyka-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next.filter((m,i)=>!(i===0&&m.role==='assistant')).slice(-20),visitorContext:{route,ghee,cool,client:'floating-anik-ai'}})});const raw=await res.text();let data={};try{data=raw?JSON.parse(raw):{}}catch{}if(!res.ok)throw new Error(data?.error||('AI server returned HTTP '+res.status+'.'));if(!data?.text)throw new Error(data?.error||'AI returned an empty response.');setMessages(prev=>[...prev,{role:'assistant',content:data.text}]);}catch(error){setMessages(prev=>[...prev,{role:'assistant',content:'LOCAL FALLBACK\\n'+(error?.message||'Provider unavailable.')+'\\n\\nTry: status, rooms, hunt, maths lab, or roast — these work without the AI server.'}]);}finally{setBusy(false);}}
  return <div className={styles.widget}>{open&&<section className={styles.window} aria-label="Anik.exe"><header className={styles.head}><div className={styles.title}><span className={styles.dog}>LY</span><div><b>ANIK.EXE</b><small>LYKA / FIELD COMPANION</small></div></div><button className={styles.close} onClick={()=>setOpen(false)} aria-label="Close Anik.exe">×</button></header><div className={styles.chips}>{starters.map(item=><button key={item} onClick={()=>ask(item)} disabled={busy}>{item}</button>)}</div><div className={styles.messages}>{messages.map((m,i)=><article key={i} className={`${styles.msg} ${m.role==='user'?styles.user:''}`}><small>{m.role==='user'?'YOU':'ANIK.EXE'}</small><p>{m.content}</p></article>)}{busy&&<article className={styles.msg}><small>ANIK.EXE</small><div className={styles.typing}><i/><i/><i/></div></article>}<div ref={endRef}/></div><form className={styles.form} onSubmit={e=>{e.preventDefault();ask(input)}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask anything…" aria-label="Ask Anik.exe anything"/><button type="submit" disabled={busy} aria-label="Send">↗</button></form><div className={styles.foot}>SERVER AI · LOCAL COMMAND FALLBACK</div></section>}<button className={styles.launch} onClick={()=>setOpen(v=>!v)} aria-label={open?'Close Anik AI':'Open Anik.exe'}><span>LY</span><i/></button></div>;
}
