'use client';
import{useEffect,useState}from'react';
import{usePathname}from'next/navigation';
import{useSite}from'./SiteProvider';
import{TransitionLink}from'./TransitionLink';
import{GlobalFX}from'./GlobalFX';
import{Danger}from'./Danger';
import{sixQuestions}from'../lib/data';
const links=[['/hq','HQ'],['/roast','Roast'],['/maths-sir','Maths'],['/mission','Orbit'],['/memes','Vault'],['/archive','Archive']];
export function Shell({children}){
 const path=usePathname();const{ghee,six,setSix}=useSite();const[menu,setMenu]=useState(false);const[cmd,setCmd]=useState(false);const[step,setStep]=useState(0);const[q,setQ]=useState(()=>sixQuestions[Math.floor(Math.random()*sixQuestions.length)]);const[msg,setMsg]=useState('');
 useEffect(()=>{document.body.classList.toggle('locked',six);return()=>document.body.classList.remove('locked')},[six]);
 useEffect(()=>{const key=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCmd(v=>!v)}if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();setCmd(true)}if(e.key==='Escape'){setCmd(false);setMenu(false)}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);
 useEffect(()=>{if(!six)return;const lock=()=>{history.pushState({six:true},'',location.href)};history.pushState({six:true},'',location.href);addEventListener('popstate',lock);const key=e=>{if(e.key==='Escape'||(e.altKey&&e.key==='ArrowLeft')||(e.altKey&&e.key==='ArrowRight')){e.preventDefault();e.stopPropagation();history.pushState({six:true},'',location.href)}};addEventListener('keydown',key,true);const before=e=>{e.preventDefault();e.returnValue='LYKA SIX MODE is still active.'};addEventListener('beforeunload',before);document.body.classList.add('six-locked');return()=>{removeEventListener('popstate',lock);removeEventListener('keydown',key,true);removeEventListener('beforeunload',before);document.body.classList.remove('six-locked')}},[six]);
 const playSixWarning=()=>{try{const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return;const ctx=new Ctx();const now=ctx.currentTime;const master=ctx.createGain();master.gain.setValueAtTime(.0001,now);master.gain.exponentialRampToValueAtTime(.12,now+.02);master.gain.exponentialRampToValueAtTime(.0001,now+.72);master.connect(ctx.destination);[440,330,220].forEach((freq,i)=>{const o=ctx.createOscillator();const g=ctx.createGain();o.type='square';o.frequency.setValueAtTime(freq,now+i*.16);g.gain.setValueAtTime(.0001,now+i*.16);g.gain.exponentialRampToValueAtTime(.08,now+i*.16+.02);g.gain.exponentialRampToValueAtTime(.0001,now+i*.16+.18);o.connect(g);g.connect(master);o.start(now+i*.16);o.stop(now+i*.16+.2)});window.setTimeout(()=>ctx.close(),900)}catch{}};
 const openSix=()=>{playSixWarning();setMenu(false);setCmd(false);setSix(true);setStep(0);setMsg('');setQ(sixQuestions[Math.floor(Math.random()*sixQuestions.length)])};
 const answer=v=>{if(v!==q.a){setStep(0);setMsg(q.wrong);setQ(sixQuestions[Math.floor(Math.random()*sixQuestions.length)]);return}const n=step+1;if(n>=5){setSix(false);setStep(0);setMsg('');return}setStep(n);setMsg(q.right+' • '+n+'/5');const pool=sixQuestions.filter(x=>x.q!==q.q);setQ(pool[Math.floor(Math.random()*pool.length)])};
 return <div className="app-shell">
 {!six&&<header className="nav-shell"><TransitionLink href="/hq" className="brand"><span className="brand-icon"><img src="/lyka-mark.svg" alt="LYKA"/></span><span className="brand-copy"><b>LYKA</b><small>FIELD SYSTEM / 032</small></span></TransitionLink><nav>{links.map(([h,l])=><TransitionLink key={h} href={h} className={path===h?'active':''}>{l}</TransitionLink>)}</nav><div className="nav-right"><span className="ghee-pill"><i/>GHEE <b>{ghee}%</b></span><button className="command-button" onClick={()=>setCmd(true)}><kbd>⌘</kbd><span>COMMAND</span><b>K</b></button><button className="index-button" onClick={()=>setMenu(v=>!v)}><i/><span>{menu?'CLOSE':'INDEX'}</span></button></div></header>}
 {menu&&!six&&<div className="nav-overlay" onClick={()=>setMenu(false)}><div className="nav-drawer premium-nav-panel" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span>LYKA / FIELD INDEX</span><small>ALL SYSTEMS • 032</small></div><button onClick={()=>setMenu(false)} aria-label="Close navigation">×</button></div><div className="drawer-hero"><small>NAVIGATION</small><h2>Choose<br/><i>your route.</i></h2><p>The entire archive, arranged properly.</p></div><div className="drawer-links">{links.concat([['/photos','Photos'],['/about','About']]).map(([h,l],i)=><TransitionLink key={h} href={h} onClick={()=>setMenu(false)}><span>{String(i+1).padStart(2,'0')}</span><strong>{l}</strong><em>↗</em></TransitionLink>)}</div><button className="drawer-six" onClick={openSix}><span>09</span><div><strong>SIX MODE</strong><small>ENTER THE LOCKDOWN</small></div><em>↗</em></button><div className="drawer-foot"><span>PRIVATE ARCHIVE / 2026</span><span>ESC TO CLOSE</span></div></div></div>
 {cmd&&!six&&<div className="command-backdrop" onClick={()=>setCmd(false)}><div className="command-panel" onClick={e=>e.stopPropagation()}><div className="command-head"><span>LYKA COMMAND</span><kbd>ESC</kbd></div><div className="command-input"><span>SEARCH LYKA</span><kbd>/</kbd></div><div className="command-grid">{links.concat([['/photos','Photos'],['/about','About']]).map(([h,l])=><TransitionLink key={h} href={h} onClick={()=>setCmd(false)}><span>{l}</span><b>↗</b></TransitionLink>)}<button onClick={openSix}><span>Six Mode</span><b>⚡</b></button></div><div className="command-foot"><span>LYKA NAVIGATION SYSTEM</span><b>ESC TO CLOSE</b></div></div></div>}
 <main>{children}</main><GlobalFX/><Danger/>
 {six&&<div className="six-root" onContextMenu={e=>e.preventDefault()}><div className="six-rain">{Array.from({length:46},(_,i)=><span key={i} style={{left:(i*19)%100+'%',animationDelay:'-'+(i%13)*.33+'s',animationDuration:3.2+(i%6)*.5+'s'}}>{i%2?'SIX / BREACH':'MEETHE LOG AA GAYE'}</span>)}</div><div className="six-panel"><div className="six-top"><span>SIX / LOCKDOWN</span><b>{step}/5</b></div><div className="six-badge">6</div><h1>MEETHE LOG<br/><i>AA GAYE.</i></h1><p>Normal navigation band. Five sahi jawab chahiye. Galat hua toh streak <b>0</b>.</p><div className="six-question"><small>SECURITY CHECK</small><h2>{q.q}</h2><div className="six-options">{q.opts.map(v=><button key={v} onClick={()=>answer(v)}>{v}</button>)}</div>{msg&&<div className="six-msg">{msg}</div>}</div><div className="six-foot">Navigation sealed • Broken by Anik's family™</div></div></div>}
 </div>
}