'use client';
import{useEffect,useState}from'react';
import{usePathname}from'next/navigation';
import{useSite}from'./SiteProvider';
import{TransitionLink}from'./TransitionLink';
import{GlobalFX}from'./GlobalFX';
import{Danger}from'./Danger';
import{sixQuestions}from'../lib/data';
const links=[['/hq','HQ'],['/roast','Roast'],['/maths-sir','Maths'],['/mission','Orbit'],['/memes','Vault'],['/archive','Archive']];
export function Shell({children}){
 const path=usePathname();const{ghee,six,setSix}=useSite();const[menu,setMenu]=useState(false);const[cmd,setCmd]=useState(false);const[step,setStep]=useState(0);const[q,setQ]=useState(()=>sixQuestions[Math.floor(Math.random()*sixQuestions.length)]);const[msg,setMsg]=useState('');
 useEffect(()=>{document.body.classList.toggle('locked',six);return()=>document.body.classList.remove('locked')},[six]);
 useEffect(()=>{const key=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCmd(v=>!v)}if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();setCmd(true)}if(e.key==='Escape'){setCmd(false);setMenu(false)}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);
 useEffect(()=>{if(!six)return;const guard=()=>history.pushState({six:true},'',location.href);history.pushState({six:true},'',location.href);addEventListener('popstate',guard);return()=>removeEventListener('popstate',guard)},[six]);
 const openSix=()=>{setMenu(false);setCmd(false);setSix(true);setStep(0);setMsg('');setQ(sixQuestions[Math.floor(Math.random()*sixQuestions.length)])};
 const answer=v=>{if(v!==q.a){setStep(0);setMsg(q.wrong);setQ(sixQuestions[Math.floor(Math.random()*sixQuestions.length)]);return}const n=step+1;if(n>=5){setSix(false);setStep(0);setMsg('');return}setStep(n);setMsg(q.right+' • '+n+'/5');const pool=sixQuestions.filter(x=>x.q!==q.q);setQ(pool[Math.floor(Math.random()*pool.length)])};
 return <div className="app-shell">
 {!six&&<header className="nav-shell"><TransitionLink href="/hq" className="brand"><span className="brand-icon"><img src="/lyka-mark.svg" alt="LYKA"/></span><span><b>LYKA</b><small>FIELD SYSTEM / 032</small></span></TransitionLink><nav>{links.map(([h,l])=><TransitionLink key={h} href={h} className={path===h?'active':''}>{l}</TransitionLink>)}</nav><div className="nav-right"><span className="ghee-pill">GHEE <b>{ghee}%</b></span><button className="menu-button" onClick={()=>setCmd(true)}>⌘ K</button><button className="menu-button" onClick={()=>setMenu(v=>!v)}>{menu?'CLOSE':'INDEX'}</button></div></header>}
 {menu&&!six&&<div className="nav-drawer"><div className="drawer-head"><span>FIELD INDEX / 032</span><button onClick={()=>setMenu(false)}>×</button></div><div className="drawer-links">{links.concat([['/photos','Photos'],['/about','About']]).map(([h,l],i)=><TransitionLink key={h} href={h} onClick={()=>setMenu(false)}><span>{String(i+1).padStart(2,'0')}</span><strong>{l}</strong><em>↗</em></TransitionLink>)}<button className="drawer-six" onClick={openSix}><span>09</span><strong>SIX MODE</strong><em>⚡</em></button></div></div>}
 {cmd&&!six&&<div className="command-backdrop" onClick={()=>setCmd(false)}><div className="command-panel" onClick={e=>e.stopPropagation()}><div className="command-head"><span>LYKA COMMAND</span><kbd>ESC</kbd></div><div className="command-input">Type a destination...</div><div className="command-grid">{links.concat([['/photos','Photos'],['/about','About']]).map(([h,l])=><TransitionLink key={h} href={h} onClick={()=>setCmd(false)}><span>{l}</span><b>↗</b></TransitionLink>)}<button onClick={openSix}><span>Six Mode</span><b>⚡</b></button></div><div className="command-foot">Press <b>⌘ K</b> anywhere to reopen</div></div></div>}
 <main>{children}</main><GlobalFX/><Danger/>
 {six&&<div className="six-root"><div className="six-rain">{Array.from({length:46},(_,i)=><span key={i} style={{left:(i*19)%100+'%',animationDelay:'-'+(i%13)*.33+'s',animationDuration:3.2+(i%6)*.5+'s'}}>{i%2?'SIX / BREACH':'MEETHE LOG AA GAYE'}</span>)}</div><div className="six-panel"><div className="six-top"><span>SIX / LOCKDOWN</span><b>{step}/5</b></div><div className="six-badge">6</div><h1>MEETHE LOG<br/><i>AA GAYE.</i></h1><p>Normal navigation band. Five sahi jawab chahiye. Galat hua toh streak <b>0</b>.</p><div className="six-question"><small>SECURITY CHECK</small><h2>{q.q}</h2><div className="six-options">{q.opts.map(v=><button key={v} onClick={()=>answer(v)}>{v}</button>)}</div>{msg&&<div className="six-msg">{msg}</div>}</div><div className="six-foot">Navigation sealed • Broken by Anik's family™</div></div></div>}
 </div>
}