"use client";
import {useEffect,useMemo,useState} from "react";
import {useSite} from "@/components/SiteProvider";
import {missionEvents} from "@/lib/jokes";
export default function Mission(){
 const {ghee,spendGhee}=useSite();
 const [launched,setLaunched]=useState(false),[angle,setAngle]=useState(0),[fuel,setFuel]=useState(92),[stability,setStability]=useState(88),[event,setEvent]=useState("Mission ready. Launch kar, space dog.");
 useEffect(()=>{if(!launched)return;const id=window.setInterval(()=>{setAngle(v=>(v+2)%360);setFuel(v=>Math.max(0,v-.06));setStability(v=>Math.max(20,Math.min(100,v+(Math.random()-.5)*1.8)));if(Math.random()<.045)setEvent(missionEvents[Math.floor(Math.random()*missionEvents.length)])},32);return()=>window.clearInterval(id)},[launched]);
 const {x,y}=useMemo(()=>{const r=(angle-90)*Math.PI/180;return{x:50+35*Math.cos(r),y:52+16*Math.sin(r)}},[angle]);
 const launch=()=>{setLaunched(true);setEvent("Ignition on. LYKA ab officially chakkar kaat raha hai.")};
 const boost=()=>{if(!launched)return;setFuel(v=>Math.max(0,v-9));setStability(v=>Math.max(10,v-4));spendGhee(5);setEvent("BOOST. Zarurat se zyada confidence detect hua.")};
 const brake=()=>{if(!launched)return;setStability(v=>Math.min(100,v+9));setEvent("Brake lag gayi. Thoda dimaag wapas aaya.")};
 const reroute=()=>{if(!launched)return;setAngle(v=>(v+67)%360);setStability(v=>Math.max(18,v-5));spendGhee(3);setEvent("Orbit reroute hua. Kahan? Kisi ko nahi pata.")};
 const reset=()=>{setLaunched(false);setAngle(0);setFuel(92);setStability(88);setEvent("Mission ready. Launch kar, space dog.")};
 return <div className="page"><header className="page-head"><span className="eyebrow">MISSION CONTROL / LYKA-01</span><h1>Earth ke <span>chakkar.</span></h1><p className="lede">Yahan satellite sach mein ghoomega. Random events aayenge, decisions fuel khaayenge, aur Ghee ka hisaab har jagah chalega.</p></header><section className="mission-card"><div className="stars"/><div className="mission-top"><span>LYKA-01 / <b>{launched?"ORBIT LIVE":"STANDBY"}</b></span><span>ANGLE {Math.round(angle)}°</span></div><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="earth"><div className="earth-glow"/><strong>EARTH</strong><small>LIVE TRACK</small></div><div className="shuttle" style={{left:`${x}%`,top:`${y}%`,transform:`translate(-50%,-50%) rotate(${angle+90}deg)`}}><i/><b/></div><div className="mission-stats"><span>FUEL<strong>{Math.round(fuel)}%</strong></span><span>STABILITY<strong>{Math.round(stability)}%</strong></span><span>GHEE<strong>{ghee}%</strong></span></div><div className="mission-console"><span className="kicker">{launched?"ORBIT ACTIVE":"MISSION READY"}</span><h2>{launched?"LYKA is roaming.":"Launch the space dog."}</h2><p>{event}</p><div className="button-row"><button className="btn primary" onClick={launch} disabled={launched}>Launch</button><button className="btn" onClick={boost} disabled={!launched}>Boost</button><button className="btn" onClick={brake} disabled={!launched}>Brake</button><button className="btn" onClick={reroute} disabled={!launched}>Reroute</button><button className="btn" onClick={()=>setStability(v=>Math.min(100,v+12))} disabled={!launched}>Stabilize</button><button className="btn ghost" onClick={reset}>Reset</button></div></div></section></div>
}
