'use client';
import{useEffect,useState}from'react';
import{jokes}from'../../lib/data';
import{Reveal}from'../../components/Reveal';
import{TransitionLink}from'../../components/TransitionLink';
import{useSite}from'../../components/SiteProvider';

const evidence=[['01','THE CONTRADICTION','Maths is somehow both favourite and worst.','DOCUMENTED'],['02','THE SIR EVENT','Maths Sir enters. Questions become personal.','RECORDED'],['03','THE ANUCHHED INCIDENT','Anu → Anuched. A syllabus escalation.','CLASSIFIED'],['04','THE PRESS CONFERENCE','One Free Fire kill. Maximum commentary.','ARCHIVED'],['05','SPACE DOG','Human classification remains pending.','UNKNOWN'],['06','GHEE RESERVE','Resource level fluctuates without explanation.','LIVE']];

export default function HQ(){
 const[joke,setJoke]=useState(jokes[0]);const{ghee,cool}=useSite();const[tab,setTab]=useState('DOSSIER');const[scan,setScan]=useState(false);const[zoom,setZoom]=useState(false);
 useEffect(()=>{const id=setInterval(()=>setJoke(jokes[Math.floor(Math.random()*jokes.length)]),2600);return()=>clearInterval(id)},[]);
 return <div className="page hq-page">
  <section className="hq-command-hero"><div className="hq-hero-index"><span>001</span><i/><span>ANIK / HQ</span></div><div className="hq-hero-copy"><span className="eyebrow">LYKA HEADQUARTERS / SUBJECT FILE 001</span><h1>ANIK<br/><em>UNDER</em><br/>OBSERVATION.</h1><p>Not a biography. A live evidence system built from photos, contradictions, study logs, chaos and suspiciously detailed records.</p><div className="hq-actions"><TransitionLink href="/photos" className="button hot">OPEN PHOTO FILES ↗</TransitionLink><button className="hq-scan-btn" onClick={()=>setScan(v=>!v)}>{scan?'CLOSE SCAN':'RUN ROOM SCAN'}</button></div></div><div className="hq-hero-visual"><div className="hq-cross"/><button className={'hq-photo-frame '+(zoom?'zoomed':'')} onClick={()=>setZoom(v=>!v)} aria-label="Zoom evidence photo"><img src="/photos/anik-02.jpeg" alt="Anik"/><span>SUBJECT / 001</span><b>{zoom?'CLOSE':'ZOOM'} ↗</b></button><div className="hq-ring ring-one"/><div className="hq-ring ring-two"/><div className="hq-coordinate">28°N<br/>77°E</div></div>{scan&&<div className="hq-scan-overlay"><span>ROOM SCAN / ACTIVE</span><b>6 RECORDS VERIFIED</b><i/><p>VISUALS: ONLINE<br/>GHEE: {ghee}%<br/>COOL: {cool}<br/>COMMON SENSE: UNCONFIRMED</p></div>}</section>{zoom&&<div className="hq-evidence-zoom" onClick={()=>setZoom(false)}><div><img src="/photos/anik-02.jpeg" alt="Anik evidence enlarged"/><span>SUBJECT 001 / VISUAL EVIDENCE / CLICK TO CLOSE</span></div></div>}
  <div className="hq-strip"><span>LYKA / HEADQUARTERS</span><b>LIVE DOSSIER</b><span>FIELD STATUS / OPERATIONAL</span></div>
  <section className="hq-switcher glass">{['DOSSIER','CHRONOLOGY','RESTRICTED'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}<span>FILE 001 / 032</span></section>
  <Reveal className="hq-body">
   {tab==='DOSSIER'&&<><div className="hq-note-panel"><span className="eyebrow">LIVE FIELD NOTE</span><strong>{joke}</strong><button onClick={()=>setJoke(jokes[Math.floor(Math.random()*jokes.length)])}>GENERATE ANOTHER ↻</button><div className="hq-meter"><span>GHEE RESERVE</span><b>{ghee}%</b><i><em style={{width:ghee+'%'}}/></i></div></div><div className="hq-evidence-list">{evidence.map(([n,t,p,s])=><article key={n}><span>{n}</span><div><small>{s}</small><h3>{t}</h3><p>{p}</p></div><b>↗</b></article>)}</div></>}
   {tab==='CHRONOLOGY'&&<div className="hq-chronology">{['THE START','THE CHAOS','THE STUDY ERA','THE ARCHIVE','THE CURRENT STATE'].map((x,i)=><article key={x}><span>0{i+1}</span><div><small>FIELD RECORD</small><h2>{x}</h2><p>{['Subject identified. The archive begins.','Evidence starts multiplying for no practical reason.','Maths becomes an unavoidable recurring event.','Photos, memes and classified material are stored.','System remains online. Questions remain unanswered.'][i]}</p></div><i/></article>)}</div>}
   {tab==='RESTRICTED'&&<div className="hq-restricted"><span className="eyebrow">ACCESS LEVEL / RESTRICTED</span><div className="redacted"><b>ANIK</b><i/><i/><i/></div><h2>The more you inspect,<br/><em>the less normal it gets.</em></h2><p>Some records are intentionally incomplete. That is not a bug.</p><div className="restricted-grid"><span>CONFIDENCE <b>HIGH</b></span><span>LOGIC <b>LOADING</b></span><span>CHAOS <b>OPTIMAL</b></span></div></div>}
  </Reveal>
  <section className="hq-bottom-grid"><div><span className="eyebrow">HQ / NEXT ROUTE</span><h2>There is more<br/><em>in the archive.</em></h2></div><TransitionLink href="/lmao" className="button hot">ENTER LMAO LAB ↗</TransitionLink></section>
 </div>
}