export const jokes=["NG detected. Confidence itni ki answer galat ho tab bhi explanation 12 minutes ka.","Bhai ka confidence 5G, answer abhi bhi loading.","Maths Sir ne question diya; bhai ne usko personal insult samajh liya.","NG ne bola “easy hai” — question ne turant difficulty badha di.","Camera on. Automatic Ban Gaya Cool protocol.","Question padhne se pehle attitude answer de deta hai.","NG ka favourite calculator button: AC. Reason: har 30 second mein reset.","Bhai revision nahi karta, bas syllabus ko emotionally support karta hai.","Ghee low hai, confidence full hai. Conservation of delusion confirmed.","NG enters the room: volume 100, preparation 37.","Ek answer sahi kya hua, commentary ka director’s cut shuru.","Maths ki copy khulti hai aur NG ka confidence airplane mode pe chala jata hai.","Bhai ne bola “maine padha tha” — archive search: NO RECORD FOUND.","NG ka study plan itna ambitious hai ki khud calendar ne resignation de diya.","Anuched ka naam sunte hi NG ka brain says: unexpected plot twist.","Bhai ka strongest subject? “Mujhe aata tha, bas exam mein yaad nahi aaya.”","NG ne shortcut poocha. Maths Sir ne bola: pehle question toh padh le.","Confidence detected. Evidence pending.","Bhai ne ek meme dekha aur usko educational resource declare kar diya.","LYKA analysis: 10% logic, 40% confidence, 50% “bhai dekh kya hua”.","NG ka attention span aur Wi-Fi signal — dono kabhi kabhi mysteriously disappear.","Bhai ne kaha “last question” aur 17 minutes baad bhi bonus round chal raha tha.","Subject file update: NG still undefeated against reading the full question.","Roast engine says: bhai tu problem solve kam, problem ko character development zyada deta hai.","Ghee tank khali hone se pehle cool meter bhar gaya.","Bhai ka exam strategy: pehle confidence, phir question, phir Bhagwan se meeting.","NG ne bola “simple tha” — ye sentence usually investigation ka beginning hota hai.","LYKA verdict: certified bakchod energy, surprisingly functional sometimes.","Bhai ka browser history nahi, browser archaeology hai.","NG ki speed: button click 100, decision making buffering.","Ek silly mistake aur bhai usko “experimental approach” bol raha hai.","Archive note: subject has repeatedly overestimated the power of “kal se pakka”.","Maths ka question dekh ke NG ka brain: terms and conditions apply.","Bhai ne timetable banaya. Timetable ne khud follow-up reminder bhej diya.","Cool level rising. Academic evidence still being located.","NG ne answer guess kiya aur confidence se us guess ko fact bana diya.","LYKA AI recommendation: pehle question padh, phir hero ban.","Bhai ki productivity ka loading screen premium hai.","Subject claims he is locked in. System telemetry says tab switching detected.","NG ka signature move: easy question ko unnecessarily cinematic banana."];
export const sixQuestions=[
 {q:'Anik ke father ka naam?',a:'Khali',opts:['Khali','Maths Sir','Lyka','Ghee'],right:'SAHI. Family file accepted.',wrong:'GALAT. Streak = 0. Khali bhi disappoint ho gaya.'},
 {q:'Anik ka favourite + worst subject?',a:'Maths',opts:['Maths','Science','English','Anuched'],right:'SAHI. Maths paradox intact.',wrong:'GALAT. Itna simple tha bhai.'},
 {q:'Anuradha ke naam se Anu ke baad?',a:'Anuched',opts:['Anuched','Orbit','Ghee','Six'],right:'SAHI. Anuched protocol online.',wrong:'GALAT. Anu tumse naraaz hai.'},
 {q:'Ghee 0% pe kya aata hai?',a:'RED DANGER',opts:['RED DANGER','Victory','Break','Bonus'],right:'SAHI. Emergency protocol safe.',wrong:'GALAT. Ghee waise hi khatam hai.'},
 {q:'Cool banne par classic response?',a:'Ban Gaya Cool',opts:['Ban Gaya Cool','Topper','Normal','Mission Success'],right:'SAHI. Cool detector active.',wrong:'GALAT. Confidence kam karo.'},
 {q:'Scientific classification?',a:'Sanki Scientist',opts:['Sanki Scientist','Pilot','Chef','Coach'],right:'SAHI. Lab approved.',wrong:'GALAT. Scientist offended.'},
];
export const maths=[
 {q:'Solve: 3x + 5 = 20',a:'5',opts:['3','5','7','10'],right:'Maths Sir: Haan bhai, dimaag ne attendance laga di.',wrong:'Maths Sir: x = 5. Arithmetic bhi kar liya karo.'},
 {q:'HCF of 36 and 48?',a:'12',opts:['6','8','12','18'],right:'Maths Sir: Theek. Aaj copy bach gayi.',wrong:'Maths Sir: 12 tha. Ganit se personal mat ho.'},
 {q:'One zero of x² − 5x + 6 is 2. Other zero?',a:'3',opts:['1','2','3','6'],right:'Maths Sir: Ab ye hui na baat.',wrong:'Maths Sir: 3 tha. Polynomial tumse zyada stable hai.'},
 {q:'Probability of an even number on a fair die?',a:'1/2',opts:['1/6','1/3','1/2','2/3'],right:'Maths Sir: Sahi. Chance tha, le liya.',wrong:'Maths Sir: 1/2. Is baar chance bhi fail ho gaya.'},
 {q:'Distance between (0,0) and (3,4)?',a:'5',opts:['4','5','6','7'],right:'Maths Sir: 3-4-5. Classic.',wrong:'Maths Sir: 5 tha bhai. Pythagoras ko tag mat kar.'},
 {q:'If x+y=10 and x−y=2, x = ?',a:'6',opts:['4','5','6','8'],right:'Maths Sir: Clean solve. Ab confidence control.',wrong:'Maths Sir: x = 6. Add-subtract seekh le.'},
 {q:'The roots of x² − 9 are?',a:'3, -3',opts:['3, -3','9, 0','3, 3','-9, 1'],right:'Maths Sir: Nice. Factorisation zinda hai.',wrong:'Maths Sir: ±3. Sign bhi syllabus ka part hai.'},
 {q:'Mean of 2, 4, 6, 8?',a:'5',opts:['4','5','6','20'],right:'Maths Sir: Average bhi nikal gaya. Respect.',wrong:'Maths Sir: Total 20 / 4 = 5. Calculator ko break do.'}
];

export const hardMaths=[
 {q:'If the roots of 2x² − 5x + k are equal, find k.',a:'25/8',opts:['5/2','25/8','8/25','25/4'],right:'Maths Sir: Discriminant = 0. Ab quadratic ne respect diya.',wrong:'Maths Sir: Equal roots means b² − 4ac = 0.'},
 {q:'Find the point dividing the line joining (−2, 3) and (4, −6) internally in ratio 2:1.',a:'(2, -3)',opts:['(2, -3)','(0, 1)','(−1, 2)','(4, −2)'],right:'Section formula survived. Clean.',wrong:'Maths Sir: Section formula. Ratio ko ulta mat kar.'},
 {q:'If tan A = 3/4, find (sin A + cos A)/(sin A − cos A), A acute.',a:'7',opts:['7','1/7','−7','5/7'],right:'Maths Sir: 3-4-5 triangle ne attendance laga di.',wrong:'Maths Sir: sin A = 3/5, cos A = 4/5. Ab simplify.'},
 {q:'The 10th term of an AP is 21 and the 21st term is 43. Find the common difference.',a:'2',opts:['1','2','3','4'],right:'AP under control. Difference = 2.',wrong:'Maths Sir: Subtract the two terms and divide by 11.'},
 {q:'A quadratic polynomial has zeroes 2 + √3 and 2 − √3. Find the polynomial.',a:'x² − 4x + 1',opts:['x² − 4x + 1','x² + 4x + 1','x² − 2x + 1','x² − 4x − 1'],right:'Nice. Sum and product both used.',wrong:'Maths Sir: Sum = 4, product = 1. Build the polynomial.'},
 {q:'If two tangents from an external point are 7 cm each, what is the distance from the point to the circle centre if radius is 24 cm?',a:'25 cm',opts:['24 cm','25 cm','31 cm','49 cm'],right:'7-24-25. Geometry classic.',wrong:'Maths Sir: Radius ⟂ tangent. Pythagoras time.'},
 {q:'A die is thrown twice. Probability that the sum is 9 is?',a:'1/9',opts:['1/6','1/9','1/12','2/9'],right:'Pairs count = 4 out of 36. Solid.',wrong:'Maths Sir: Ordered pairs (3,6),(4,5),(5,4),(6,3).'},
 {q:'If sec θ + tan θ = 3, find sec θ − tan θ.',a:'1/3',opts:['3','1/3','2/3','1'],right:'Maths Sir: Product identity. Short and deadly.',wrong:'Maths Sir: (sec θ + tan θ)(sec θ − tan θ) = 1.'},
 {q:'The area of a sector of 90° in a circle of radius 14 cm is (π = 22/7):',a:'154 cm²',opts:['77 cm²','154 cm²','308 cm²','616 cm²'],right:'Quarter circle. 154 cm².',wrong:'Maths Sir: 90° means one-fourth of the circle.'},
 {q:'For the pair 2x + 3y = 7 and 4x + 6y = 14, the number of solutions is:',a:'Infinitely many',opts:['No solution','One','Infinitely many','Two'],right:'Same line. Infinite solutions.',wrong:'Maths Sir: Second equation is exactly 2× the first.'},
 {q:'If the mean of 5 observations is 18 and one observation 22 is replaced by 12, the new mean is:',a:'16',opts:['14','16','18','20'],right:'Mean dropped by 2. Correct.',wrong:'Maths Sir: Total drops by 10; 10/5 = 2.'},
 {q:'A cone and cylinder have equal radii and equal heights. Ratio of their volumes is:',a:'1:3',opts:['1:2','1:3','2:3','3:1'],right:'πr²h/3 vs πr²h. Easy marks.',wrong:'Maths Sir: Cone volume is one-third of cylinder volume.'}
];
export const orbitEvents=['Maths Sir transmission: “Question simple tha.”','Sanki Scientist: biscuit propulsion approved.','Ghee telemetry: budget sambhal, bhai.','Earth control: “Wapas aa ja.”','Trajectory stable. Confidence questionable.','Dog signal detected in low orbit.','Solar flare alert. Thoda seedha ud, bhai.'];
