'use client';
import { useEffect, useRef, useState } from 'react';
import { Reveal } from '../../components/Reveal';

const quotes=['Bhai ne button dekha aur immediately press kar diya.','Scientific accuracy: questionable. Entertainment: approved.','Anik.exe has stopped making normal decisions.','Ghee levels critical. Confidence levels completely unaffected.'];
const secrets=['KYA DEKH RAHE HO 👀','404: COMMON SENSE NOT FOUND','GOPAL SIR HAS ENTERED THE CHAT','ANIK DETECTED. ABORT MISSION.','THIS BUTTON DOES NOTHING. PROBABLY.'];

export default function LmaoLab(){
 const [game,setGame]=useState('reaction'),[target,setTarget]=useState({x:50,y:50}),[hits,setHits]=useState(0),[time,setTime]=useState(15),[running,setRunning]=useState(false),[best,setBest]=useState(0),[quote,setQuote]=useState(quotes[0]),[math,setMath]=useState(null),[mathScore,setMathScore]=useState(0),[mathTime,setMathTime]=useState(4),[secret,setSecret]=useState(null),[egg,setEgg]=useState(0),timer=useRef(null),mathTimer=useRef(null);
 useEffect(()=>()=>{clearInterval(timer.current);clearInterval(mathTimer.current)},[]);
 const randomSecret=()=>{if(Math.random()<.24)setSecret(secrets[Math.floor(Math.random()*secrets.length)])};
 const startReaction=()=>{clearInterval(timer.current);setHits(0);setTime(15);setRunning(true);timer.current=setInterval(()=>setTime(v=>{if(v<=1){clearInterval(timer.current);setRunning(false);return 0}return v-1}),1000)};
 const hit=()=>{if(!running)return;setHits(v=>{const n=v+1;setBest(b=>Math.max(b,n));return n});setTarget({x:8+Math.random()*84,y:10+Math.random()*80});randomSecret()};
 const newMath=()=>{clearInterval(mathTimer.current);const a=11+Math.floor(Math.random()*40),b=7+Math.floor(Math.random()*25),ans=a*b;setMath({a,b,answer:ans,opts:[ans,ans+7,ans-9,a+b].sort(()=>Math.random()-.5)});setMathTime(4);mathTimer.current=setInterval(()=>setMathTime(v=>{if(v<=.1){clearInterval(mathTimer.current);setMath(null);setQuote('TIMEOUT. Maths Sir is disappointed.');return 4}return +(v-.1).toFixed(1)}),100)};
 const answerMath=v=>{if(!math)return;if(v===math.answer)setMathScore(s=>s+1);else setMathScore(s=>Math.max(0,s-1));setQuote(v===math.answer?'SAHI. Rare footage.':'GALAT. Calculator ko blame mat kar.');newMath()};
 const tab=id=>{setGame(id);setSecret(null);if(id==='math'){setMath(null);clearInterval(mathTimer.current)}};
 return <div className="page lmao-page">
  <div className="page-hero lmao-hero"><div className="page-title"><span className="eyebrow">ROOM 09 / LMAO LAB / CLASSIFIED ENTERTAINMENT</span><h1>Nothing useful.<br/><em>Maximum difficulty.</em></h1><p className="lede">Ten hidden systems. Three games. Almost nobody should complete this.</p></div><div className="lmao-stamp">NO<br/>SKILL<br/>ISSUE</div></div>
  <div className="lmao-tabs glass">{[['reaction','GHEE CATCH'],['math','MATH PANIC'],['quote','ANIK.EXE']].map(([id,label])=><button key={id} className={game===id?'active':''} onClick={()=>tab(id)}>{label}</button>)}</div>
  <Reveal className="lmao-grid">
   {game==='reaction'&&<div className="glass lmao-game reaction-game"><div className="game-head"><span className="eyebrow">01 / NIGHTMARE REFLEX</span><b>{time}s</b></div><div className="reaction-arena"><div className="reaction-copy"><small>HARD MODE / TARGET SHRINKS</small><strong>{hits}</strong><span>hits / 15 seconds • target moves faster</span></div>{running?<button className="ghee-target" style={{left:target.x+'%',top:target.y+'%',transform:'translate(-50%,-50%) scale('+Math.max(.38,1-hits*.025)+')'}} onClick={hit}>G</button>:<button className="start-orb" onClick={startReaction}>{time===0?'RETRY':'START'}</button>}{secret&&<div className="lmao-secret-pop">{secret}</div>}</div><div className="game-foot"><span>BEST / {best}</span><span>PERFECT RUN = 45+ HITS</span></div></div>}
   {game==='math'&&<div className="glass lmao-game math-panic"><div className="game-head"><span className="eyebrow">02 / NIGHTMARE CALCULATION</span><b>{mathScore} correct</b></div><div className="panic-core">{!math?<><small>4 SECOND LIMIT / WRONG = -1</small><h2>Survive<br/><em>Math Panic.</em></h2><button className="button hot" onClick={newMath}>ENTER NIGHTMARE →</button></>:<><span className="panic-timer">{mathTime.toFixed(1)}s</span><h2>{math.a} × {math.b} = ?</h2><div className="panic-options">{math.opts.map(v=><button key={v} onClick={()=>answerMath(v)}>{v}</button>)}</div></>}</div><div className="game-foot"><span>STREAK / {mathScore}</span><span>10 CORRECT = SECRET</span></div></div>}
   {game==='quote'&&<div className="glass lmao-game exe-game"><div className="game-head"><span className="eyebrow">03 / ANIK.EXE / CHAOS MODE</span><b>10 EASTER EGGS</b></div><div className="exe-screen"><div className="terminal-lines"><span>BOOTING ANIK.EXE...</span><span>CONFIDENCE ........ 100%</span><span>LOGIC ............. LOADING</span><span>GHEE .............. {hits>2?'CRITICAL':'STABLE'}</span><span>COMMON SENSE ...... NOT FOUND</span><span>HIDDEN FEATURES ... {egg}/10</span></div><h2>{quote}</h2><button className="button hot" onClick={()=>{setHits(v=>v+1);setEgg(v=>Math.min(10,v+1));setQuote(quotes[Math.floor(Math.random()*quotes.length)]);randomSecret()}}>RUN AGAIN ↻</button>{secret&&<div className="lmao-secret-pop">{secret}</div>}</div></div>}
  </Reveal>
  <div className="lmao-bottom"><span>LYKA RESEARCH DEPARTMENT</span><b>{egg>=10?'ALL SECRETS FOUND':'10 HIDDEN FEATURES / GOOD LUCK'}</b><span>STATUS / VERY ONLINE</span></div>
 </div>;
}