'use client';
import { useEffect, useRef, useState } from 'react';
import { Reveal } from '../../components/Reveal';

const quotes=['POV: Anik ne RUN AGAIN dabaya aur aura farming ho gayi.','Bhai is actually LOCKED IN 💀','6-7. Bas itna hi bolunga.','Maths Sir dekh rahe hain. Calculator bhi.','Expectation: easy. Reality: bhai cooked.','No context. No logic. Full confidence.','Aura +100, common sense -100.','Bro said let him cook and forgot the gas.'];
const secrets=['KYA DEKH RAHE HO 👀','404: COMMON SENSE NOT FOUND','MATHS SIR HAS ENTERED THE CHAT','ANIK DETECTED. ABORT MISSION.','THIS BUTTON DOES NOTHING. PROBABLY.']; const hints=['Look where LYKA first introduces itself.','A module that measures confidence is hiding something.','The flight deck has more than one route.','The archive has a door that looks too ordinary.','The Maths Lab has a number that is not a score.','Photos have more than pictures.','The HQ has a classified corner.','The navigation system remembers things.','The final page is not really the end.','LMAO Lab itself is hiding the last one.'];

export default function LmaoLab(){
 const[askOpen,setAskOpen]=useState(false),[askText,setAskText]=useState(''),[askSent,setAskSent]=useState(false),[game,setGame]=useState('reaction'),[terms,setTerms]=useState(true),[found,setFound]=useState([]),[hintOpen,setHintOpen]=useState(false),[target,setTarget]=useState({x:50,y:50}),[hits,setHits]=useState(0),[time,setTime]=useState(15),[running,setRunning]=useState(false),[best,setBest]=useState(0),[quote,setQuote]=useState(quotes[0]),[math,setMath]=useState(null),[mathScore,setMathScore]=useState(0),[mathQ,setMathQ]=useState(0),[mathTime,setMathTime]=useState(4),[mathDone,setMathDone]=useState(false),[mathFinal,setMathFinal]=useState(0),[secret,setSecret]=useState(null),[egg,setEgg]=useState(0),timer=useRef(null),mathTimer=useRef(null),mathScoreRef=useRef(0),mathQRef=useRef(0);
 useEffect(()=>{try{setFound(JSON.parse(localStorage.getItem('lyka-hunt')||'[]'))}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem('lyka-hunt',JSON.stringify(found))}catch{}},[found]);
 useEffect(()=>()=>{clearInterval(timer.current);clearInterval(mathTimer.current)},[]);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setTarget({x:10+Math.random()*80,y:14+Math.random()*72}),600+Math.random()*300);return()=>clearInterval(id)},[running]);
 const discover=()=>{const n=found.length;if(n>=10)return;setFound(v=>[...v,n]);setSecret(n===9?'🏆 ALL 10 FOUND — ₹100 REWARD UNLOCKED.':'SECRET '+(n+1)+' FOUND — '+(9-n)+' REMAINING')};
 const randomSecret=()=>{if(Math.random()<.18)setSecret(secrets[Math.floor(Math.random()*secrets.length)])};
 const startReaction=()=>{clearInterval(timer.current);setHits(0);setTime(15);setRunning(true);setSecret(null);timer.current=setInterval(()=>setTime(v=>{if(v<=1){clearInterval(timer.current);setRunning(false);return 0}return v-1}),1000)};
 const hit=()=>{if(!running)return;setHits(v=>{const n=v+1;setBest(b=>Math.max(b,n));return n});setTarget({x:10+Math.random()*80,y:14+Math.random()*72});randomSecret()};
 const newMath=(n=mathQRef.current+1)=>{clearInterval(mathTimer.current);const a=11+Math.floor(Math.random()*40),b=7+Math.floor(Math.random()*25),ans=a*b;const opts=[ans,ans+7,Math.max(1,ans-9),a+b].sort(()=>Math.random()-.5);setMath({a,b,answer:ans,opts});setMathTime(5);setMathQ(n);mathQRef.current=n;mathTimer.current=setInterval(()=>setMathTime(v=>Math.max(0,v-0.1)),100);setTimeout(()=>{if(mathQRef.current===n)timeoutMath(n)},5050);};
 const startMath=()=>{clearInterval(mathTimer.current);mathScoreRef.current=0;mathQRef.current=0;setMathScore(0);setMathQ(0);setMathDone(false);setMathFinal(0);setQuote(quotes[egg%quotes.length]);newMath(1)};
 const finishMath=score=>{clearInterval(mathTimer.current);setMath(null);setMathDone(true);setMathFinal(score);setQuote(score>=8?'Maths Sir has questions. You apparently have answers.':score>=5?'Not terrible. The calculator remains disappointed.':'That score has been reported to Maths Sir. Good luck.');
 };
 const answerMath=v=>{if(!math)return;const next=Math.max(-10,mathScore+(v===math.answer?1:-2));mathScoreRef.current=next;setMathScore(next);setQuote(v===math.answer?['SAHI. Aura maintained.','Bhai actually cooked.','Maths Sir ne attendance laga di.'][Math.floor(Math.random()*3)]:['GALAT. Bhai -2 gaya.','Calculator ne resignation de diya.','POV: question padhna optional samajh liya.'][Math.floor(Math.random()*3)]);if(mathQRef.current>=10)finishMath(next);else newMath()};
 const timeoutMath=(n)=>{if(n!==mathQRef.current||!math)return;const next=mathScoreRef.current;mathScoreRef.current=next;setMathScore(next);setQuote('TIMEOUT. Next question. No negative marking.');if(n>=10)finishMath(next);else newMath(n+1)};
 const tab=id=>{setGame(id);setSecret(null);if(id==='math'){clearInterval(mathTimer.current);setMath(null);setMathDone(false)}};
 const scoreLine=s=>s>=10?'10/10 — Maths Sir ne attendance laga di. Ab ghar ja aur kuch mat kar.':s>=8?'8–9/10 — Aaj toh bhai ne syllabus ki dhulai kar di. Kal phir aukaat check hogi.':s>=6?'6–7/10 — Nice try son. Maths ne bola: abhi picture baaki hai.':s>=4?'4–5/10 — Itna confidence kis baat ka tha? Answer sheet abhi bhi ro rahi hai.':s>=2?'2–3/10 — Bhai ne calculator ko bhi emotional damage de diya.':'0–1/10 — Excellent. Question paper ne tujhe dekha aur bola: rehne de bhai.';
 return <div className="page lmao-page">
  <div className="page-hero lmao-hero"><div className="page-title"><span className="eyebrow">ROOM 09 / LMAO LAB / CLASSIFIED ENTERTAINMENT</span><h1>Nothing useful.<br/><em>Maximum difficulty.</em></h1><p className="lede">Three games. One questionable lab. Your score will be remembered.</p></div><div className="lmao-stamp">NO<br/>SKILL<br/>ISSUE</div></div>
  <div className="lmao-rewardbar"><b>10 SECRET LOCATIONS</b><span>{found.length}/10 FOUND · {10-found.length} REMAINING</span><button onClick={()=>setHintOpen(v=>!v)}>{hintOpen?'HIDE HINTS':'SHOW HINTS'}</button></div>
  {hintOpen&&<div className="secret-hints glass">{hints.map((h,i)=><div key={i} className={found.includes(i)?'found':''}><b>{String(i+1).padStart(2,'0')}</b><span>{found.includes(i)?'✓ SECRET FOUND':h}</span></div>)}</div>}
  {terms&&<div className="terms-overlay"><div className="terms-card"><span className="eyebrow">LYKA / LMAO LAB / TERMS</span><h2>Before you<br/><em>break your brain.</em></h2><p>There are 10 hidden secrets. Hints are available, but the locations are not handed to you. Find all 10 and the site promises a <b>₹100 reward from Archit</b>.</p><div className="terms-list"><span>01 / Games are intentionally difficult.</span><span>02 / Secret locations may be weird or random.</span><span>03 / Progress is saved on this browser.</span><span>04 / Reward is a fun in-site challenge promise, not a guaranteed platform payment.</span></div><button className="button hot" onClick={()=>setTerms(false)}>I ACCEPT — LET ME IN ↗</button></div></div>}
  <div className="lmao-tabs glass">{[['reaction','GHEE CATCH'],['math','MATH PANIC'],['quote','ANIK.EXE']].map(([id,label])=><button key={id} className={game===id?'active':''} onClick={()=>tab(id)}>{label}</button>)}</div>
  <Reveal className="lmao-grid">
   {game==='reaction'&&<div className="glass lmao-game reaction-game"><div className="game-head"><span className="eyebrow">01 / GHEE CATCH / REFLEX LAB</span><b>{time}s</b></div><div className="reaction-arena"><div className="reaction-copy"><small>PRECISION MODE / SLOWER TARGET / MISCLICK = 0</small><strong>{hits}</strong><span>hits / 15 seconds • best {best}</span></div>{running?<button className="ghee-target" style={{left:target.x+'%',top:target.y+'%',transform:'translate(-50%,-50%) scale('+Math.max(.62,1-hits*.009)+')'}} onClick={hit}>G</button>:<button className="start-orb" onClick={startReaction}>{time===0?'TRY AGAIN':'START'}</button>}{secret&&<div className="lmao-secret-pop">{secret}</div>}</div><div className="game-foot"><span>SCORE / {hits}</span><span>BEST / {best}</span><span>{hits>=25?'ABSOLUTE LOCK-IN.':'TARGET MOVES — CATCH IT.'}</span>{hits>=5&&<button className="ask-archit" onClick={()=>{setAskOpen(true);setAskSent(false)}}>ASK ARCHIT ANYTHING ↗</button>}</div>{askOpen&&<div className="ask-archit-panel"><b>5 HITS UNLOCKED</b><p>Ask Archit anything.</p><input value={askText} onChange={e=>setAskText(e.target.value)} placeholder="Type your question…" autoFocus/><button onClick={()=>setAskSent(true)}>SEND QUESTION</button>{askSent&&<small>QUESTION QUEUED ✓</small>}</div>}</div>}
   {game==='math'&&<div className="glass lmao-game math-panic"><div className="game-head"><span className="eyebrow">02 / MATH PANIC / 10-QUESTION RUN</span><b>{mathDone?mathFinal:mathScore} SCORE</b></div><div className="panic-core">{!math&&!mathDone?<><small>10 QUESTIONS / 5 SECOND LIMIT / WRONG = 0 / TIMEOUT = 0</small><h2>Survive<br/><em>Math Panic.</em></h2><button className="button hot" onClick={startMath}>START 10-QUESTION RUN →</button></>:mathDone?<div className="math-result"><small>RUN COMPLETE / 10 OF 10</small><strong>{mathFinal}<span>/10</span></strong><h2>{scoreLine(mathFinal)}</h2><p>{quote}</p><button className="button hot" onClick={startMath}>DO IT AGAIN ↻</button></div>:<><span className="panic-timer">{mathTime.toFixed(1)}s</span><small>QUESTION {mathQ} / 10</small><h2>{math.a} × {math.b} = ?</h2><div className="panic-options">{math.opts.map(v=><button key={v} onClick={()=>answerMath(v)}>{v}</button>)}</div></>}</div><div className="game-foot"><span>SCORE / {mathDone?mathFinal:mathScore}</span><span>QUESTION / {mathDone?10:mathQ}</span><span>{mathDone?'KEEP GOING. YOU CAN RUN IT AGAIN.':'NO MERCY.'}</span></div></div>}
   {game==='quote'&&<div className="glass lmao-game exe-game"><div className="game-head"><span className="eyebrow">03 / ANIK.EXE / CHAOS MODE</span><b>{egg}/10 EASTER EGGS</b></div><div className="exe-screen"><div className="terminal-lines"><span>BOOTING ANIK.EXE...</span><span>CONFIDENCE ........ 100%</span><span>LOGIC ............. LOADING</span><span>GHEE .............. {hits>2?'CRITICAL':'STABLE'}</span><span>COMMON SENSE ...... NOT FOUND</span><span>HIDDEN FEATURES ... {egg}/10</span></div><h2>{quote}</h2><button className="button hot" onClick={()=>{setHits(v=>v+1);setEgg(v=>Math.min(10,v+1));setQuote(quotes[Math.floor(Math.random()*quotes.length)]);randomSecret()}}>RUN AGAIN ↻</button>{secret&&<div className="lmao-secret-pop">{secret}</div>}</div></div>}
  </Reveal>
  <div className="lmao-bottom"><span>LYKA RESEARCH DEPARTMENT</span><b>{egg>=10?'ALL SECRETS FOUND':'10 HIDDEN FEATURES / GOOD LUCK'}</b><span>STATUS / VERY ONLINE</span></div>
 </div>;
}